export enum Race {
  AngelCommand = "angelCommand",
  ApolloniaDragon = "apolloniaDragon",
  ArcSeraphim = "arcSeraphim",
  ArmoredDragon = "armoredDragon",
  ArmoredWyvern = "armoredWyvern",
  Armorloid = "armorloid",
  BalloonMushroom = "balloonMushroom",
  BeastFolk = "beastFolk",
  Berserker = "berserker",
  BigMuscle = "bigMuscle",
  BlueMonster = "blueMonster",
  BrainJacker = "brainJacker",
  BraveSpirit = "braveSpirit",
  LiquidPeople = "liquidPeople",
  LightBringer = "lightBringer",
}
