import type { Creature } from '@kaijudo/react-game-types'
import { Civilization, Rarity, Race } from '@kaijudo/react-game-types'

import {
  aquaHulcus,
  astrocometDragon,
  boltailDragon,
  bronzeArmTribe,
  burningMane,
  deathbladeBeetle,
  deadlyFighterBraidClaw,
  explosiveFighterUcarn,
  fatalAttackerHorvath,
  fonchTheOracle,
  gigastand,
  greatestEarthPlanetaryDragon,
  grimSoulShadowOfReversal,
  immortalBaronVorg,
  larbaGeerTheImmaculate,
  marrowOozeTheTwister,
  metalwingSkyterror,
  mieleVizierOfLightning,
  pyrofighterMagnus,
  rimuelCloudbreakerElemental,
  rippleLotusQ,
  roaringGreatHorn,
  stardustNexElementalDragonKnight,
  supernovaPlutoDeathbringer,
  technoTotem,
} from '@kaijudo/react-card-images'

export interface CollectionCard extends Creature {
  imageSrc: string
}

export const allCards: CollectionCard[] = [
  {
    id: 'aqua-hulcus',
    name: 'Aqua Hulcus',
    civilization: Civilization.Water,
    manaCost: 3,
    power: 2000,
    toughness: 1,
    race: Race.LiquidPeople,
    rarity: Rarity.Common,
    abilities: ['When you put this creature into the battle zone, draw a card.'],
    imageSrc: aquaHulcus,
  },
  {
    id: 'astrocomet-dragon',
    name: 'Astrocomet Dragon',
    civilization: Civilization.Fire,
    manaCost: 7,
    power: 9000,
    toughness: 1,
    race: Race.ArmoredDragon,
    rarity: Rarity.Rare,
    abilities: ['Double breaker'],
    imageSrc: astrocometDragon,
  },
  {
    id: 'boltail-dragon',
    name: 'Boltail Dragon',
    civilization: Civilization.Fire,
    manaCost: 6,
    power: 5000,
    toughness: 1,
    race: Race.ArmoredDragon,
    rarity: Rarity.Uncommon,
    abilities: ['Speed attacker'],
    imageSrc: boltailDragon,
  },
  {
    id: 'bronze-arm-tribe',
    name: 'Bronze-Arm Tribe',
    civilization: Civilization.Nature,
    manaCost: 3,
    power: 1000,
    toughness: 1,
    race: Race.BeastFolk,
    rarity: Rarity.Common,
    abilities: ['When you put this creature into the battle zone, put the top card of your deck into your mana zone.'],
    imageSrc: bronzeArmTribe,
  },
  {
    id: 'burning-mane',
    name: 'Burning Mane',
    civilization: Civilization.Fire,
    manaCost: 4,
    power: 3000,
    toughness: 1,
    race: Race.Berserker,
    rarity: Rarity.Common,
    abilities: ['Power attacker +2000'],
    imageSrc: burningMane,
  },
  {
    id: 'deathblade-beetle',
    name: 'Deathblade Beetle',
    civilization: Civilization.Nature,
    manaCost: 5,
    power: 4000,
    toughness: 1,
    race: Race.BigMuscle,
    rarity: Rarity.Uncommon,
    abilities: ['Power attacker +4000'],
    imageSrc: deathbladeBeetle,
  },
  {
    id: 'deadly-fighter-braid-claw',
    name: 'Deadly Fighter Braid Claw',
    civilization: Civilization.Fire,
    manaCost: 2,
    power: 1000,
    toughness: 1,
    race: Race.Berserker,
    rarity: Rarity.Common,
    abilities: ['Speed attacker', 'This creature attacks each turn if able.'],
    imageSrc: deadlyFighterBraidClaw,
  },
  {
    id: 'explosive-fighter-ucarn',
    name: 'Explosive Fighter Ucarn',
    civilization: Civilization.Fire,
    manaCost: 5,
    power: 5000,
    toughness: 1,
    race: Race.Berserker,
    rarity: Rarity.Rare,
    abilities: ['Speed attacker'],
    imageSrc: explosiveFighterUcarn,
  },
  {
    id: 'fatal-attacker-horvath',
    name: 'Fatal Attacker Horvath',
    civilization: Civilization.Fire,
    manaCost: 4,
    power: 4000,
    toughness: 1,
    race: Race.Berserker,
    rarity: Rarity.Uncommon,
    abilities: ['This creature attacks each turn if able.'],
    imageSrc: fatalAttackerHorvath,
  },
  {
    id: 'fonch-the-oracle',
    name: 'Fonch, the Oracle',
    civilization: Civilization.Light,
    manaCost: 4,
    power: 3000,
    toughness: 1,
    race: Race.LightBringer,
    rarity: Rarity.Common,
    abilities: ['Blocker'],
    imageSrc: fonchTheOracle,
  },
  {
    id: 'gigastand',
    name: 'Gigastand',
    civilization: Civilization.Darkness,
    manaCost: 5,
    power: 4000,
    toughness: 1,
    race: Race.BrainJacker,
    rarity: Rarity.Uncommon,
    abilities: ['Slayer'],
    imageSrc: gigastand,
  },
  {
    id: 'greatest-earth-planetary-dragon',
    name: 'Greatest Earth, Planetary Dragon',
    civilization: Civilization.Nature,
    manaCost: 8,
    power: 12000,
    toughness: 1,
    race: Race.ApolloniaDragon,
    rarity: Rarity.SuperRare,
    abilities: ['Triple breaker'],
    imageSrc: greatestEarthPlanetaryDragon,
  },
  {
    id: 'grim-soul-shadow-of-reversal',
    name: 'Grim Soul, Shadow of Reversal',
    civilization: Civilization.Darkness,
    manaCost: 3,
    power: 2000,
    toughness: 1,
    race: Race.BrainJacker,
    rarity: Rarity.Common,
    abilities: ['When this creature is destroyed, your opponent discards a card.'],
    imageSrc: grimSoulShadowOfReversal,
  },
  {
    id: 'immortal-baron-vorg',
    name: 'Immortal Baron, Vorg',
    civilization: Civilization.Fire,
    manaCost: 2,
    power: 2000,
    toughness: 1,
    race: Race.Berserker,
    rarity: Rarity.Common,
    imageSrc: immortalBaronVorg,
  },
  {
    id: 'larba-geer-the-immaculate',
    name: 'Larba Geer, the Immaculate',
    civilization: Civilization.Light,
    manaCost: 5,
    power: 3500,
    toughness: 1,
    race: Race.AngelCommand,
    rarity: Rarity.Rare,
    abilities: ['Blocker'],
    imageSrc: larbaGeerTheImmaculate,
  },
  {
    id: 'marrow-ooze-the-twister',
    name: 'Marrow Ooze, the Twister',
    civilization: Civilization.Darkness,
    manaCost: 2,
    power: 1000,
    toughness: 1,
    race: Race.BrainJacker,
    rarity: Rarity.Common,
    abilities: ['Blocker', 'This creature can\'t attack.'],
    imageSrc: marrowOozeTheTwister,
  },
  {
    id: 'metalwing-skyterror',
    name: 'Metalwing Skyterror',
    civilization: Civilization.Fire,
    manaCost: 6,
    power: 4000,
    toughness: 1,
    race: Race.ArmoredWyvern,
    rarity: Rarity.Rare,
    abilities: ['When you put this creature into the battle zone, destroy all blockers.'],
    imageSrc: metalwingSkyterror,
  },
  {
    id: 'miele-vizier-of-lightning',
    name: 'Miele, Vizier of Lightning',
    civilization: Civilization.Light,
    manaCost: 3,
    power: 2000,
    toughness: 1,
    race: Race.ArcSeraphim,
    rarity: Rarity.Common,
    abilities: ['When you put this creature into the battle zone, tap one of your opponent\'s creatures.'],
    imageSrc: mieleVizierOfLightning,
  },
  {
    id: 'pyrofighter-magnus',
    name: 'Pyrofighter Magnus',
    civilization: Civilization.Fire,
    manaCost: 3,
    power: 3000,
    toughness: 1,
    race: Race.Berserker,
    rarity: Rarity.Common,
    abilities: ['Speed attacker', 'At the end of the turn, destroy this creature.'],
    imageSrc: pyrofighterMagnus,
  },
  {
    id: 'rimuel-cloudbreaker-elemental',
    name: 'Rimuel, Cloudbreaker Elemental',
    civilization: Civilization.Light,
    manaCost: 7,
    power: 8000,
    toughness: 1,
    race: Race.AngelCommand,
    rarity: Rarity.VeryRare,
    abilities: ['Double breaker', 'Blocker'],
    imageSrc: rimuelCloudbreakerElemental,
  },
  {
    id: 'ripple-lotus-q',
    name: 'Ripple Lotus Q',
    civilization: Civilization.Water,
    manaCost: 2,
    power: 1000,
    toughness: 1,
    race: Race.BlueMonster,
    rarity: Rarity.Common,
    imageSrc: rippleLotusQ,
  },
  {
    id: 'roaring-great-horn',
    name: 'Roaring Great-Horn',
    civilization: Civilization.Nature,
    manaCost: 6,
    power: 8000,
    toughness: 1,
    race: Race.BigMuscle,
    rarity: Rarity.Uncommon,
    abilities: ['Double breaker'],
    imageSrc: roaringGreatHorn,
  },
  {
    id: 'stardust-nex-elemental-dragon-knight',
    name: 'Stardust NEX, Elemental Dragon Knight',
    civilization: Civilization.Light,
    manaCost: 9,
    power: 11000,
    toughness: 1,
    race: Race.ApolloniaDragon,
    rarity: Rarity.SuperRare,
    abilities: ['Triple breaker', 'Blocker'],
    imageSrc: stardustNexElementalDragonKnight,
  },
  {
    id: 'supernova-pluto-deathbringer',
    name: 'Supernova Pluto Deathbringer',
    civilization: Civilization.Darkness,
    manaCost: 10,
    power: 15000,
    toughness: 1,
    race: Race.ApolloniaDragon,
    rarity: Rarity.SuperRare,
    abilities: ['Triple breaker', 'When you put this creature into the battle zone, destroy all other creatures.'],
    imageSrc: supernovaPlutoDeathbringer,
  },
  {
    id: 'techno-totem',
    name: 'Techno Totem',
    civilization: Civilization.Water,
    manaCost: 4,
    power: 3000,
    toughness: 1,
    race: Race.Armorloid,
    rarity: Rarity.Common,
    abilities: ['Blocker', 'This creature can\'t attack.'],
    imageSrc: technoTotem,
  },
]
